### PR TITLE
Batch1

### PR DESCRIPTION
**Pull request by mmazur**
These changes + adding a 'language!=EN detector' would imho warrant a v6 release.

### CODE REVIEW

**Comment by mgsloan** [comment]
Thanks!  I forgot to push my changes that already made it into v6.  Is sorting by assignee very important?  I wish I could figure out a good way to automate updating the firefox extension.  Releasing the chrome extension is fully automated, but the firefox upload still takes a minute or two.

**Comment by mmazur** [comment]
Well, as far as end user experience is concerned, I was hoping for three changes:
- WHAT_CURSOR_APPLIES_TO = 'all'; already pushed
- drop version mismatch warning entirely; todoist gets new updates waay too often for this to makes sense; you just pushed 891, today 892 came out
- instead have a warning that suggests a potential version issue or using a non-EN UI when a menu item (id/class/text) can't be found, since that's an actual indication that something is wrong and stuff won't work

As to firefox – sorry, no idea. I've authored only one standalone extension, it's for chrome, and it's still loaded in dev mode from a file on disk, cause I never bothered to publish it. :)

**Comment by mgsloan** [comment]
> drop version mismatch warning entirely; todoist gets new updates waay too often for this to makes sense; you just pushed 891, today 892 came out

Yeah maybe that was a bit of overengineering on my part. I didn't realize the frequency that todoist is being updated, and none of the changes have broken todoist-shortcuts yet.  I wrote it to make as few assumptions as possible about the DOM.

One option I like would be to have some file in the repo which has info about known breakages / known working versions.  However, yes, that might be overkill.

> instead have a warning that suggests a potential version issue or using a non-EN UI when a menu item (id/class/text) can't be found, since that's an actual indication that something is wrong and stuff won't work

Such a warning does pop up in the developer console, but yes, it should probably be in the UI itself.

**Comment by mmazur** [comment]
UI-altering changes in todoist are rare, while versions get bumped very often. So a warning system that notices expected UI elements missing makes sense (especially for all the people not using the English UI for whom the extension will just not work without any explanation why), while one that just nags about the version number not matching will just be plain irritating and of no use.

If the system would be smart enough, it'd:
- complain only about likely new unsupported version if the class/id matching function can't find something
- complain about possible unsupported version *and* language if the text-matching function can't find something

I'm pretty sure you'd apply such a change much quicker and much cleaner than I would (I don't actually know JS, it's just that modifying existing codebase is relatively easy even for somebody completely unfamiliar with the language), though if you don't get around to it, I will eventually – I strongly believe we'll be losing a lot of potential users, since most people won't bother going to the code to figure out why half of the commands don't work (the language thing).

**Comment by mgsloan** [comment]
It's an interesting idea to check assumptions and produce a UI warning if the assumptions are violated.  Could just have some of the current uses of warning / error do this.  However, that is more work!  Instead, I have defaulted to hiding away the warning under the settings menu and making it clear that it is usually not a problem.

**Pull request merged**
