### PR TITLE
Add follow function

### PR DESCRIPTION
**Pull request by mdbraber**
As I often want to open links directly I added a "follow" function to open the current link under the cursor

### CODE REVIEW

**Comment by mgsloan** [comment]
Good idea!  For future contributions if'd be ideal if you ran `./eslint.sh` and resolved the issues it reports.  I don't mind fixing it though (I wish more maintainers would just fix things they want changed in PRs instead of fixing it themselves - seems more efficient!)

**Comment by mgsloan** [comment]
I use this all the time now - great idea!

**Comment by mgsloan** [comment]
I've released this, it is now included in version 17 :+1:

**Comment by mdbraber** [comment]
Great! (Honestly I've transitioned back to Things 3, but it's good to hear this is being used :-)

**Pull request merged**
